name: Go

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: action/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Simple Test
        run: |
          ./dummy-server.bin &
          sleep 3
          curl -s https://localhost:8443
          kill $!
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./dummy-server.bin

